server:
  port: 8081
spring:
  main:
      web-application-type: REACTIVE
  config:
    import: file:.env[.properties]
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml



jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600 #seconds
  issuer: avraam112russo